# Generated by Django 2.1 on 2018-08-13 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post1',
            old_name='title',
            new_name='title1',
        ),
    ]
