# Generated by Django 2.1 on 2018-08-13 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180814_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post1',
            old_name='text',
            new_name='text1',
        ),
    ]
