# Generated by Django 2.1 on 2018-08-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_editorial_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editorial',
            old_name='created_date',
            new_name='edit_created_date',
        ),
        migrations.RenameField(
            model_name='editorial',
            old_name='published_date',
            new_name='edit_published_date',
        ),
        migrations.RenameField(
            model_name='editorial',
            old_name='text',
            new_name='edit_text',
        ),
        migrations.RenameField(
            model_name='editorial',
            old_name='title',
            new_name='edit_title',
        ),
    ]
