# Generated by Django 2.1 on 2018-08-17 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20180814_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post1',
            old_name='text1',
            new_name='text',
        ),
    ]
